### ISSUE TITLE
Refactoring Shapes using variables 

### ISSUE THREAD

**Issue by aschultz25** [aschultz25/introduction-to-shapes#1]
When using variables in your code, you define common properties among the shapes like size, position, and color. This makes the code a lot easier to modify, because instead of changing each individual code of multiple shapes, you can just edit the variable. 

When multiple shapes have common properties, using a variable is going to get rid of the constant repition, which will make the code more clear and manageable. @mrjloswald-avenues

**Comment by mrjloswald-avenues** [comment]
This is really amazing! I'd argue, though, that your use of variables here is more akin to the way we used parameters for the previous assignment. Consider this line of your code: 

`rect(210, 170, armWidth, 210)`

`armWidth` is a good variable to use here, because you have two arms. But, those other values should probably be variables as well! Probably proportions relative to your bounding box. 

At any rate, this is very good!
